# SPDX-FileCopyrightText: 2026 Ian Lumsden
#
# SPDX-License-Identifier: MIT

import argparse
from pathlib import Path

import tomli_w

from reuse_license_utils.commands.command_base import Command
from reuse_license_utils.toml import generate_reuse_toml


class GenerateReuseTomlCommand(Command):
    def __init__(self) -> None:
        super().__init__("generate-toml", "Generate a REUSE.toml based on the config")

    def _add_subcommand_specific_arguments(self) -> None:
        self.parser.add_argument(
            "--reuse-toml-file",
            "-f",
            type=Path,
            default=None,
            help=(
                "The path to the REUSE.toml file that will be generated."
                "If not provided, this flag defaults to `<repo_root>/REUSE.toml`."
            ),
        )

    def _run_impl(self, args: argparse.Namespace) -> None:
        # Identify the path to REUSE.toml
        reuse_toml_file_path = args.reuse_toml_file
        if args.reuse_toml_file is None:
            reuse_toml_file_path = self.repo_root / "REUSE.toml"
        reuse_toml_file_path = reuse_toml_file_path.expanduser().resolve()
        # Create a header for the generated REUSE.toml
        reuse_toml_header = "\n".join(
            [
                "# Generated by reuse-license-utils.",
                "# Declares licensing information for files that cannot or should not",
                "# include SPDX headers.",
                "# If a warning was produced in generating the contents of this file,",
                "# there are likely files you have missed in the reuse-license-utils config,",
                "# which will result in `reuse lint` failing.",
                "",
            ],
        )
        # Create the REUSE.toml contents and dump it to a string
        reuse_toml_data = generate_reuse_toml(self.repo_root, self.config)
        reuse_toml_contents = tomli_w.dumps(reuse_toml_data)
        # Prepend the header to the contents of REUSE.toml
        reuse_toml_contents = reuse_toml_header + reuse_toml_contents
        # Write the contents to REUSE.toml
        with reuse_toml_file_path.open("w") as f:
            f.write(reuse_toml_contents)
        print(f"The REUSE.toml file has been written to {reuse_toml_file_path}.")
