from reuse_license_utils.config import LicenseUtilsConfig


def generate_reuse_toml(config: LicenseUtilsConfig) -> str:
    """Generate the contents of a REUSE.toml based on the config."""
    lines = [
        "# Generated by reuse-license-utils.",
        "# Declares licensing information for files that cannot or should not",
        "# include SPDX headers.",
        "# If a warning was produced in generating the contents of this file,",
        "# there are likely files you have missed in the reuse-license-utils config,",
        "# which will result in `reuse lint` failing.",
        "",
        "version = 1",
        "",
    ]

    for path_config in config.reuse_toml_paths:
        copyright_holder = path_config.copyright_holder
        if path_config.copyright_holder is None:
            copyright_holder = config.default_copyright_holder
        if copyright_holder is None:
            raise ValueError(
                "Either the `default_copyright_holder` or the `copyright_holder` field for the REUSE.toml configuration must be provided.",  # noqa: E501
            )
        copyright_years = path_config.copyright_years
        if path_config.copyright_years is None:
            copyright_years = config.default_copyright_years
        if copyright_years is None:
            raise ValueError(
                "Either the `default_copyright_years` or the `copyright_years` field for the REUSE.toml configuration must be provided.",  # noqa: E501
            )
        license_id = path_config.license_id
        if path_config.license_id is None:
            license_id = config.default_license_id
        if license_id is None:
            raise ValueError(
                "Either the `default_license_id` or the `license_id` field for the REUSE.toml configuration must be provided.",  # noqa: E501
            )
        lines += [
            "[[annotations]]",
            f'path = "{path_config.path}"',
            f'SPDX-FileCopyrightText = "{copyright_years} {copyright_holder}"',
            f'SPDX-License-Identifier = "{license_id}"',
            "",
        ]

    # TODO add a step where I call a TBA function in verify.py that will check if the files
    #      in the config match the files that should be included in REUSE.toml

    return "\n".join(lines)
